//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Individual_Client()
        {
            this.Client_Purpose = new HashSet<Client_Purpose>();
            this.Payment_Client = new HashSet<Payment_Client>();
            this.Work_Shedule = new HashSet<Work_Shedule>();
        }
    
        public int Client_ID { get; set; }
        public byte[] Image { get; set; }
        public string National_ID { get; set; }
        public string Father_Name { get; set; }
        public string Mother_Name { get; set; }
        public string Present_Address { get; set; }
        public string Permanent_Address { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Tin_Number { get; set; }
        public string Email { get; set; }
        public string Fact_of_Case { get; set; }
        public string Phone_Number { get; set; }
        public string Reference_Name { get; set; }
        public string Auto_Generate_Name { get; set; }
        public Nullable<System.DateTime> Tax_of_year { get; set; }
        public string Bank_of_Name { get; set; }
        public string Bank_Account_Number { get; set; }
        public string Type_of_Account { get; set; }
        public Nullable<System.DateTime> Period_of_AccountDate { get; set; }
        public string Information_of_SavingAccount { get; set; }
        public string Other_Account { get; set; }
        public byte[] Import_Export_PaperImage { get; set; }
        public string Car_Details { get; set; }
        public string Assets_Class { get; set; }
        public string Amount_of_Assets { get; set; }
        public string Price_of_Assets { get; set; }
        public string Amount_of_HomeArea { get; set; }
        public string Floor_Number { get; set; }
        public string Renter_Number { get; set; }
        public string Renter_Contract { get; set; }
        public string Self_Living { get; set; }
        public string Flat_Details { get; set; }
        public string Invest_Details { get; set; }
        public string Shareholding_Details { get; set; }
        public string BOI_Account { get; set; }
        public string Partner_Details { get; set; }
        public string Credit_Card_Details { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Purpose> Client_Purpose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Client> Payment_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_Shedule> Work_Shedule { get; set; }
    }
}
