//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lawer_DatabaseEntities : DbContext
    {
        public Lawer_DatabaseEntities()
            : base("name=Lawer_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client_Purpose> Client_Purpose { get; set; }
        public virtual DbSet<Employee_Register> Employee_Register { get; set; }
        public virtual DbSet<Family_Costing> Family_Costing { get; set; }
        public virtual DbSet<Individual_Client> Individual_Client { get; set; }
        public virtual DbSet<Office_Costing> Office_Costing { get; set; }
        public virtual DbSet<Other_Information> Other_Information { get; set; }
        public virtual DbSet<Payment_Client> Payment_Client { get; set; }
        public virtual DbSet<School_Costing> School_Costing { get; set; }
        public virtual DbSet<School_Income> School_Income { get; set; }
        public virtual DbSet<Work_Shedule> Work_Shedule { get; set; }
    }
}
