//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Income
    {
        public int School_IncomeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Income { get; set; }
        public string Reason { get; set; }
    }
}
